package com.cnepay.springstudy.mapper;

import com.cnepay.springstudy.domain.ChannelTemplateBodyConfig;

public interface ChannelTemplateBodyConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_body_config
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_body_config
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int insert(ChannelTemplateBodyConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_body_config
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int insertSelective(ChannelTemplateBodyConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_body_config
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    ChannelTemplateBodyConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_body_config
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int updateByPrimaryKeySelective(ChannelTemplateBodyConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_body_config
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int updateByPrimaryKey(ChannelTemplateBodyConfig record);
}