package com.cnepay.springstudy.mapper;

import com.cnepay.springstudy.domain.ChannelTemplateHeadConfig;

public interface ChannelTemplateHeadConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_head_config
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_head_config
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int insert(ChannelTemplateHeadConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_head_config
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int insertSelective(ChannelTemplateHeadConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_head_config
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    ChannelTemplateHeadConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_head_config
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int updateByPrimaryKeySelective(ChannelTemplateHeadConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_head_config
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int updateByPrimaryKey(ChannelTemplateHeadConfig record);
}