package com.cnepay.springstudy.mapper;

import com.cnepay.springstudy.domain.Channel;

import java.util.List;

public interface ChannelMapper {

    List<Channel> findAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int insert(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int insertSelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    Channel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int updateByPrimaryKeySelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int updateByPrimaryKey(Channel record);
}