package com.aa.springstudy.mapper;

import com.aa.springstudy.domain.ChannelTemplate;

public interface ChannelTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int insert(ChannelTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int insertSelective(ChannelTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    ChannelTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int updateByPrimaryKeySelective(ChannelTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int updateByPrimaryKey(ChannelTemplate record);
}