package com.aa.springstudy.mapper;

import com.aa.springstudy.domain.TemplateBody;

public interface TemplateBodyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_body
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_body
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int insert(TemplateBody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_body
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int insertSelective(TemplateBody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_body
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    TemplateBody selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_body
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int updateByPrimaryKeySelective(TemplateBody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_body
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int updateByPrimaryKey(TemplateBody record);
}