package com.aa.springstudy.mapper;

import com.aa.springstudy.domain.TemplateHead;

public interface TemplateHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_head
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_head
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int insert(TemplateHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_head
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int insertSelective(TemplateHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_head
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    TemplateHead selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_head
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int updateByPrimaryKeySelective(TemplateHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_head
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int updateByPrimaryKey(TemplateHead record);
}