package com.aa.springstudy.mapper;

import com.aa.springstudy.domain.UserChannel;

public interface UserChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_channel
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_channel
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int insert(UserChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_channel
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int insertSelective(UserChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_channel
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    UserChannel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_channel
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int updateByPrimaryKeySelective(UserChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_channel
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    int updateByPrimaryKey(UserChannel record);
}