package com.cnepay.springstudy.domain;

public class ChannelTemplateConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_template_config.id
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_template_config.channel_template_id
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    private Long channelTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_template_config.template_context_code
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    private String templateContextCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_template_config.template_head_code
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    private String templateHeadCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_template_config.id
     *
     * @return the value of channel_template_config.id
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_template_config.id
     *
     * @param id the value for channel_template_config.id
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_template_config.channel_template_id
     *
     * @return the value of channel_template_config.channel_template_id
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    public Long getChannelTemplateId() {
        return channelTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_template_config.channel_template_id
     *
     * @param channelTemplateId the value for channel_template_config.channel_template_id
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    public void setChannelTemplateId(Long channelTemplateId) {
        this.channelTemplateId = channelTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_template_config.template_context_code
     *
     * @return the value of channel_template_config.template_context_code
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    public String getTemplateContextCode() {
        return templateContextCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_template_config.template_context_code
     *
     * @param templateContextCode the value for channel_template_config.template_context_code
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    public void setTemplateContextCode(String templateContextCode) {
        this.templateContextCode = templateContextCode == null ? null : templateContextCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_template_config.template_head_code
     *
     * @return the value of channel_template_config.template_head_code
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    public String getTemplateHeadCode() {
        return templateHeadCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_template_config.template_head_code
     *
     * @param templateHeadCode the value for channel_template_config.template_head_code
     *
     * @mbg.generated Mon Jun 03 17:25:15 CST 2019
     */
    public void setTemplateHeadCode(String templateHeadCode) {
        this.templateHeadCode = templateHeadCode == null ? null : templateHeadCode.trim();
    }
}